name: hb
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  slide_to_confirm: ^1.1.0
  intl: ^0.20.2
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
flutter_launcher_icons:
    android: "launcher_icon"
    image_path: "assets/images/iPark logo.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/images/iPark logo.png"
    min_sdk_android: 23

    flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/chris-lee-70l1tDAI6rM-unsplash.png
    - assets/images/plane white.png
    - assets/images/irix.logo.png
    - assets/images/Vector.png
    - assets/images/qr.png
    - assets/images/Photo by Petr.png
    - assets/images/Frame 103.png
    - assets/images/Ellipse 3.png
    - assets/images/Line 11.png
    - assets/images/Facebook.png
    - assets/images/Instagram.png
    - assets/images/X.png
    - assets/images/angry emoji.png
    - assets/images/lovedIt.png
    - assets/images/sad.png
    - assets/images/satisfied.png
    - assets/images/image 146.png
    - assets/images/image 145.png
    - assets/images/iPark logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
    - family: Poppins-Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf